### ISSUE TITLE
Doesn't work for Microsoft Hyper-V

### ISSUE THREAD

**Issue by Ryan-King02** [JayMontana36/vBoxSysInfoMod#14]
It doesn't seem to detect my Hyper-V VM. Am I doing something wrong, or is this just not implemented?

**Comment by JayMontana36** [comment]
It's for VirtualBox (vBox) VMs, no others are supported by this script (otherwise there'd be other variants of this for them or the name would change to be inclusive of the others supported).

You can however run a vBox VM within a Hyper-V VM if you'd like (you can use this script in a Hyper-V VM on a vBox VM residing within one), but that's kinda pointless and you'd be better off just straight up using vBox on host rather than vBox in VM.
