### ISSUE TITLE
Version 6 of the program blocked by Avast Antivirus

### ISSUE THREAD

**Issue by TheMCNerd2017** [JayMontana36/vBoxSysInfoMod#8]
The title basically explains the issue I'm experiencing. Avast is blocking me from running the program, saying the program might be dangerous.
![blockedprogram](https://user-images.githubusercontent.com/25375242/42405559-346d687e-8166-11e8-8c29-21ceb50799e3.PNG)
The warning can be bypassed by clicking 'I trust this file' in the advanced settings of the popup, but I thought I would bring this issue to your attention, as it could scare off people from using the program.

**Comment by JayMontana36** [comment]
Unfortunately there really isn't much if even anything that I can do about it, other than to provide both the source code and the compiler (along with the compiler's settings) used to make/build/create the executable, all of which I've done; every version of vBoxSysInfoMod, including the first original version had false positives, and this is what I've done in order to combat that, so that people can review the source themselves and compile it using all of the same settings that I used (which should result in their unofficially compiled binary executable version matching my officially compiled and released binary executable versions, indicating that no changes were made/there is no difference between that unofficial version vs my officially released version, though I haven't actually tested that to be honest to see if that's the case so this is all theoretical but assuming that the compiler doesn't add anything extra like time based or anything it should match up exactly verifying it) and the compiler itself can also be used or tested for other stuff as well. Downloading the source in it's entirety and extracting/running/opening any part of it has no false positives, it's only when you compile it where you get false positives. While I could just simply release the source version solo being that you can run it without compilation, it's meant to be more of a one click zero hassle solution (releasing it as is without compiling it requires you to manually run as admin for it to work and the code could potentially be changed unintentionally somehow probably by accident while checking/reviewing it or in some cases programs check/read and modify certain files of certain types which would cause it to not work); it also makes things easier for me to debug as I can simply ask what version and OS it's running on, how you're running it/what you're doing exactly, etc instead of also an exact copy of the script to verify line for line that nothing was changed and if it was run as admin and all. All I can do is to both advise that it is a false positive as well as to link/guide them to the source code and compiler. 
![image](https://user-images.githubusercontent.com/6281870/42406034-0d85311c-816e-11e8-8250-4af9f0fe80ce.png)
^Windows Defender^
I guess/suppose what I can do instead is adopt a new packaging/distribution system, which would basically be a plain ZIP containing a false positive advisory, links to both my site and my source code, etc as well as an encrypted ZIP containing the actual/normal executables along with the password to decrypt and access it since I've seen that method of distribution used plenty of times before; thanks for the heads up though I'm aware.

**Comment by JayMontana36** [comment]
Both a new repository and dowload page were created over at https://github.com/JayMontana36/vBoxSysInfoModRepack and https://sites.google.com/site/jaymontana36jasen/downloadcenter/vBoxSysInfoModRepack for hosting and redistributing not new but the same vBoxSysInfoMod executables however using a different method effectively protecting the entire distribution and the executable itself from false potitive flags/warnings when/while downloading or attempting to download, also adding a warning within the distribution itself before ever actually granting access to the executable.
