### ISSUE TITLE
Cross-Platform

### ISSUE THREAD

**Issue by labsvisual** [JayMontana36/vBoxSysInfoMod#9]
Hey! 

I am working on a cross-platform solution in Java since no user apart from those with Win can run this! I hope it's fine?

**Comment by JayMontana36** [comment]
It's fine; you can do pretty much anything you like with it, so long as you follow the guidelines of the license.

In terms of it being cross-platform, I had been told by someone that you would get it working by using WINE and symbolic links, though I've never tested any of that myself, but the reason it isn't currently cross-platform I'll admit is in part to laziness, not just the command differences; in fact though I could just simply create an extremely simple bash script that would work on both Linux and Mac OS X, it just would have to be edited manually for the values you want and overall won't at all be on the same level as it's Windows batch equivalent, at least until I had the extra time and dedication to figure out all the bash equivalents.

Also, in order to simply things a lot, I'd recommend taking a look at the vBoxSysInfoModHistory repo (which will be a lot easier to look through than the revisions in this repo to find relevant things you need), with v5 being the minimum for the same level of capabilities v6's "ModifyVM" has, looking back at older versions for reference to what's changed if you need to, though of course you may use any part of any version you want (the easiest would be the original v1 though it lacks a ton of current functionality meanwhile v6 would be more difficult having the most functionality and having to refer back to older revisions if something doesn't make sense immediately). But yeah, feel free to do pretty much whatever you want however you want with it; as long as you're following the license terms I have no problem with it, I'll even help out a bit when/where I can if you have any questions or need help with something in my code.

**Comment by JayMontana36** [comment]
Closing for the time being due to inactivity.
